logging:
  level:
    org:
      springframework :
        transaction :
          interceptor : trace
        jdbc:
          datasource:
            DataSourceTransactionManager : debug
        orm:
          jpa:
            JpaTransactionManager : debug
      hibernate:
        resource:
          transaction: debug

spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 704315565692-049dij7cgg9s45pv3ivsls8u5hfnj67f.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: 2f33c322fa2ea88d5491d135116bb835
            client-secret: JtGMdTe1QoqdqBuU2XaWKVAGmMbLrLVP
            scope:
              - profile_nickname
              - account_email
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao :
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token